obj-$(CONFIG_TOUCHSCREEN_GT9XX)   += gt9xx_driver.o
gt9xx_driver-objs := gt9xx.o gt9xx_update.o goodix_tool.o
EXTRA_CFLAGS += -Wno-unused
EXTRA_CFLAGS += -Wno-error=date-time  # Fix compile error on gcc 4.9 and later
